// <auto-generated />
namespace StudentPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class StudentWithCourses_relation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentWithCourses_relation));
        
        string IMigrationMetadata.Id
        {
            get { return "201902050947022_StudentWithCourses_relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
